abbr --add gs 'git status'
abbr --add ga 'git add'
abbr --add gc 'git commit'
abbr --add gp 'git push'
abbr --add gl 'git log'
abbr --add gd 'git diff'
abbr --add gco 'git checkout'
abbr --add gcb 'git checkout -b'
abbr --add gcm 'git commit -m'
abbr --add gpl 'git pull'
abbr --add gcl 'git clone'
abbr --add gss 'git stash'
abbr --add gsp 'git stash pop'
abbr --add gsa 'git stash apply'
abbr --add gss 'git stash show'
abbr --add gsl 'git stash list'
abbr --add gsd 'git stash drop'
abbr --add gsc 'git stash clear'