abbr --add k 'kubectl'
abbr --add kgp 'kubectl get pods'
abbr --add kgs 'kubectl get svc'
abbr --add kgd 'kubectl get deployments'
abbr --add kgn 'kubectl get nodes'
abbr --add kga 'kubectl get all'
abbr --add kdp 'kubectl describe pod'
abbr --add kds 'kubectl describe svc'
abbr --add kdd 'kubectl describe deployment'
abbr --add kdn 'kubectl describe node'
abbr --add kl 'kubectl logs'
abbr --add ke 'kubectl exec -it'
abbr --add kpf 'kubectl port-forward'
abbr --add krm 'kubectl delete'
abbr --add kcp 'kubectl config use-context'
abbr --add kcc 'kubectl config current-context'
abbr --add kca 'kubectl config get-contexts'
abbr --add kcs 'kubectl config set-context'
abbr --add kccn 'kubectl config rename-context'
abbr --add kccr 'kubectl config delete-context'
abbr --add kctx 'kubectl config get-contexts -o name | fzf | xargs kubectl config use-context'